### ISSUE TITLE
Doesn't work on Windows 7.

### ISSUE THREAD

**Issue by rexim** [rexim/Loprog#2]
Stack trace:

```
> sbt "run example/animals.loprog"
[info] Set current project to Loprog (in build file:/D:/Programming/mine/Loprog/)
[info] Running ru.org.codingteam.loprog.Main examples/animals.loprog
java.lang.NoClassDefFoundError: Could not initialize class org.fusesource.jansi.internal.Kernel32
    at org.fusesource.jansi.internal.WindowsSupport.getConsoleMode(WindowsSupport.java:48)
    at jline.WindowsTerminal.getConsoleMode(WindowsTerminal.java:176)
    at jline.WindowsTerminal.init(WindowsTerminal.java:80)
    at jline.TerminalFactory.create(TerminalFactory.java:93)
    at jline.TerminalFactory.get(TerminalFactory.java:151)
    at ru.org.codingteam.loprog.LoprogRepl$.launch(LoprogRepl.scala:26)
    at ru.org.codingteam.loprog.Main$.main(Main.scala:6)
    at ru.org.codingteam.loprog.Main.main(Main.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at scala.tools.nsc.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:71)
    at scala.tools.nsc.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
    at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:139)
    at scala.tools.nsc.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:71)
    at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:139)
    at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:28)
    at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:45)
    at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:35)
    at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:45)
    at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:74)
    at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:96)
    at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:105)
    at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
java.lang.RuntimeException: Nonzero exit code returned from runner: 1
    at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run 'last compile:run' for the full output.
[error] (compile:run) Nonzero exit code returned from runner: 1
[error] Total time: 1 s, completed 07.04.2013 18:25:08
```

Probably, something related to jansi and its native libraries.

**Comment by rexim** [comment]
@rexim I'm really sorry, but Windows 7 is not supported anymore by Microsoft
